### ISSUE TITLE
Blank on error /?module=whmcs by error in controller.ext.php 

### ISSUE THREAD

**Issue by altomarketing** [Rynoxx/sentora-whmcs#2]
Fresh install in Sentora 1.0.3 , still did not install on whmcs

/?module=whmcs gives blank

tail -5 /var/sentora/logs/sentora-error.log gives:

`[Wed Dec 23 12:53:40.036402 2015] [:error] [pid 18137] [client 186.22.101.205:22657] PHP Fatal error:  Can't use function return value in write context in /etc/sentora/panel/modules/whmcs/code/controller.ext.php on line 265, referer: http://MYSERVER/?module=updates`

**Comment by Rynoxx** [comment]
Hi,

Try changing line 265 in 
|/etc/sentora/panel/modules/whmcs/code/controller.ext.php| to

         $zpdomain = ctrl_options::GetSystemOption('zpanel_domain');
         $isSentora = empty($zpdomain);

If that solves your problem I'll push an update to the Git and zppy 
directory


On 23/12/15 13:55, Altomarketing.com wrote:
>
> Fresh install in Sentora 103 , still did not install on whmcs
>
> /?module=whmcs gives blank
>
> tail -5 /var/sentora/logs/sentora-errorlog gives:
>
> |[Wed Dec 23 12:53:40036402 2015] [:error] [pid 18137] [client 
> 18622101205:22657] PHP Fatal error: Can't use function return value in 
> write context in 
> /etc/sentora/panel/modules/whmcs/code/controllerextphp on line 265, 
> referer: http://MYSERVER/?module=updates|
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Rynoxx/sentora-whmcs/issues/2>.
>

-- 

Best Regards,
Lukas 'Rynoxx' Söder
CTO
Grid-Servers LTD <https://grid-servers.net/>

------------------------------------------------------------------------

Grid Servers LTD is a company registered in England and Wales.
Registered number: 9324655.
Registered office: Grid-Servers, 8 Castle walk, Didcot, OX11 7PD

This email and any files transmitted with it are confidential and 
intended solely for the use of the individual or entity to whom they are 
addressed. If you have received this email in error please notify the 
system manager. This message contains confidential information and is 
intended only for the individual named. If you are not the named 
addressee you should not disseminate, distribute or copy this e-mail. 
Please notify us by forwarding this email to emailerror@grid-servers.net 
if you have received this e-mail by mistake and delete this e-mail from 
your system. If you are not the intended recipient you are notified that 
disclosing, copying, distributing or taking any action in reliance on 
the contents of this information is strictly prohibited

Any views or opinions presented in this email are solely those of the 
author and do not necessarily represent those of the company. Employees 
of Grid Servers LTD are expressly required not to make defamatory 
statements and not to infringe or authorize any infringement of 
copyright or any other legal right by email communications. Any such 
communication is contrary to company policy and outside the scope of the 
employment of the individual concerned. The company will not accept any 
liability in respect of such communication, and the employee responsible 
will be personally liable for any damages or other liability arising.

Warning: Although the company has taken reasonable precautions to ensure 
no viruses are present in this email, the company cannot accept 
responsibility for any loss or damage arising from the use of this email 
or attachments.

**Comment by altomarketing** [comment]
Now:
`[Wed Dec 23 13:30:16.626996 2015] [:error] [pid 18199] [client 186.22.101.205:21089] PHP Fatal error:  Can't use function return value in write context in /etc/sentora/panel/modules/whmcs/code/controller.ext.php on line 472, referer: http://MYHOST`

**Comment by Rynoxx** [comment]
Hi,
Changing line 472 to
             $zpdomain = ctrl_options::GetSystemOption('zpanel_domain');
             $domain = empty($zpdomain) ? 
ctrl_options::GetSystemOption('sentora_domain') : $zpdomain;

Should solve that. And hopefully those two lines were the only 
occurances of that set of code.

On 23/12/15 14:32, Altomarketing.com wrote:
>
> Now:
> |[Wed Dec 23 13:30:16.626996 2015] [:error] [pid 18199] [client 
> 186.22.101.205:21089] PHP Fatal error: Can't use function return value 
> in write context in 
> /etc/sentora/panel/modules/whmcs/code/controller.ext.php on line 472, 
> referer: http://MYHOST|
>
> —
> Reply to this email directly or view it on GitHub 
> <https://github.com/Rynoxx/sentora-whmcs/issues/2#issuecomment-166896421>.
>

-- 

Best Regards,
Lukas 'Rynoxx' Söder
CTO
Grid-Servers LTD <https://grid-servers.net/>

------------------------------------------------------------------------

Grid Servers LTD is a company registered in England and Wales.
Registered number: 9324655.
Registered office: Grid-Servers, 8 Castle walk, Didcot, OX11 7PD

This email and any files transmitted with it are confidential and 
intended solely for the use of the individual or entity to whom they are 
addressed. If you have received this email in error please notify the 
system manager. This message contains confidential information and is 
intended only for the individual named. If you are not the named 
addressee you should not disseminate, distribute or copy this e-mail. 
Please notify us by forwarding this email to emailerror@grid-servers.net 
if you have received this e-mail by mistake and delete this e-mail from 
your system. If you are not the intended recipient you are notified that 
disclosing, copying, distributing or taking any action in reliance on 
the contents of this information is strictly prohibited

Any views or opinions presented in this email are solely those of the 
author and do not necessarily represent those of the company. Employees 
of Grid Servers LTD are expressly required not to make defamatory 
statements and not to infringe or authorize any infringement of 
copyright or any other legal right by email communications. Any such 
communication is contrary to company policy and outside the scope of the 
employment of the individual concerned. The company will not accept any 
liability in respect of such communication, and the employee responsible 
will be personally liable for any damages or other liability arising.

Warning: Although the company has taken reasonable precautions to ensure 
no viruses are present in this email, the company cannot accept 
responsibility for any loss or damage arising from the use of this email 
or attachments.

**Comment by altomarketing** [comment]
It works ! Thanks
