### ISSUE TITLE
WHMCS Sentora Module Error

### ISSUE THREAD

**Issue by JustSentora** [Rynoxx/sentora-whmcs#5]
Hi,

i have download your sentora module and whmcs module project and install it like instructions in readme.txt but now sentora module works fine when i go to whmcs products/services and go to edit service e.g WEB Package 1 it say me this:

**Fatal error: Can't use method return value in write context in /var/www/html/modules/servers/sentora/sentora.php on line 400**

When i delete this line i become this:

**The site (my site) does not work**

PS: Do not do it because I have not yet added server to whmcs??

**Comment by Rynoxx** [comment]
Hi, which version of PHP are you running? Anything lower than 5.4 wont function properly, and you shouldn't really be running anything lower than 5.6 as they've reached end of life

**Comment by JustSentora** [comment]
Hi, i have now updated from 5.4 to 5.6 and still not working :(

**Comment by Rynoxx** [comment]
Could you post line 398-402 of your sentora.php here? I can't find anything on line 400 of the latest sentora.php that should be causing any trouble

**Comment by JustSentora** [comment]
Yes, 

	**$groupid = "3"; # Default to Client no need to have an else statement for this.
	if ($params["configoption2"] === "on" || stripos($producttype, "reseller") !== false){
		$groupid = "2";
	}**

But now is not that error now is just this 

http://prntscr.com/cm79yx

All works fine complete all modules but when i upload sentora nothing more in configproducts.php working just blank page with this up

**Comment by Rynoxx** [comment]
Ok, change it to the following
```
$groupid = "3"; # Default to Client no need to have an else statement for this.
$isReseller = stripos($producttype, "reseller");
if ($params["configoption2"] === "on" || $isReseller !== false){
    $groupid = "2";
}
```

And read the error logs of your webserver/php to see why the blank page shows up, it usually indicates a fatal PHP error, might be solved using the above code though

**Comment by JustSentora** [comment]
I have updated that but still not working... when i delete sentora module all works fine when i upload only configproducts.php in edit porudct mod stop working

**Comment by JustSentora** [comment]
How can i enable php error log? I go to Setup > General Settings > Other and enable Display Errors but where display it that errors? i dont know how to see what is problem

**Comment by JustSentora** [comment]
Can you help me?

________________________________

**Comment by Rynoxx** [comment]
Enabling that setting in WHMCS would show the errors instead of the page you showed in the screenshot, other than that there would be a log file located somewhere in /var/log depending on what webserver you're using

**Comment by JustSentora** [comment]
I don't have log folder on site when i go only says that picture i have send to you... How can i fix error?

**Comment by Rynoxx** [comment]
The previous error you mentioned should've been solved by the code I sent before, you'd have to look in the log file generated by your webserver, which webserver are you running? Apache?

**Comment by JustSentora** [comment]
Yes, Apache Centos 6 64Bit

**Comment by Rynoxx** [comment]
Then generally the log files for apache can be found in /var/log/httpd/, unless configured otherwise, e.g. Sentora drops log files in /var/sentora/logs/domains/USERNAME

The error log file itself should be called something along the lines of error.log or error_log, or perhaps DOMAIN-error.log

**Comment by JustSentora** [comment]
I have nothing found in error log in /var/log/httpd/ i dont know what to do...

**Comment by Rynoxx** [comment]
Odd, double check that you haven't configured it to be something else, also check /var/log/apache/

**Comment by JustSentora** [comment]
HI, i have activated sentora module but where can i now find API Key for server?

**Comment by Rynoxx** [comment]
You can find it when going to the module in Sentora, there is a button which says "API Key" press it and it'll show the API key for your sentora installation

**Comment by ItsGageHolland** [comment]
I'm also having the same issue as described above. I'm using PHP 5.4. How can I fix the "Can't use method return value in write context" error?
Thanks.

**Comment by Rynoxx** [comment]
@ItsGageHolland As PHP 5.4 has reached its end of life sometime last year ( http://php.net/supported-versions.php ), I recommend updating to at least PHP 5.6, if that doesn't work, try the solution I sent to JustSentora in the 5th reply. And get back to me with the result

**Comment by ItsGageHolland** [comment]
@Rynoxx Updating to PHP 5.6 seemed to do the trick. Thanks.
